source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '13.6'
use_frameworks!
inhibit_all_warnings!

def phenix
  pod 'PhenixSdk', '2023.0.0-d27f937-20231206T135815138-beta.6'
  pod 'PhenixDebug', :path => '../PhenixDebug'
  pod 'PhenixDeeplink', :path => '../PhenixDeeplink'
end

target 'ChannelPublisher' do
  phenix
  pod 'SwiftLint', '~> 0.49.1'
end
