source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '13.6'
use_frameworks!
inhibit_all_warnings!

def phenix
  pod 'PhenixSdk', '2024.4.0-7441191-20240906T213259024'
  pod 'PhenixDebug', :path => '../PhenixDebug'
  pod 'PhenixDeeplink', :path => '../PhenixDeeplink'
end

target 'ChannelPublisher' do
  phenix
  pod 'SwiftLint', '~> 0.49.1'
end
